### ISSUE TITLE
Dagger 2

### ISSUE THREAD

**Issue by qazt482** [kidinov/weather-app#1]
Hi,

I'm trying to learn Dagger 2 and looked over your example.

A few things:
1. In the App class the injection is unnecessary so i removed it and the corresponding method in RepositoryComponent.
2. The builder code in App does not need remoteDataSourceModule or localDataSourceModule.
3. Pretty much all of your @Provides methods (except the one in ApplicationModule) can be made static.

After these changes, the app still works.

**Comment by kidinov** [comment]
Hi,

I'm glad for you!

Thank you.
